heat_template_version: 2016-04-08

parameters:
  server_name:
    description: How to call the server
    type: string
  server_image:
    description: ID or name of the glance image to boot from
    type: string
  ssh_key:
    description: ID or name of your ssh key. Must exist in your OpenStack account.
    type: string
  secgrp:
    description: security group to use
    type: string
  network:
    description: network to use
    type: string
  ipv4_subnet:
    description: IPv4 subnet
    type: string
  ipv6_subnet:
    description: IPv6 subnet
    type: string
  ipv4_lb_pool:
    description: IPv4 LoadBalancerPool
    type: string
  ipv6_lb_pool:
    description: IPv6 LoadBalancerPool
    type: string
  availability_zone:
    description: Availability Zone to spawn server in
    type: string

resources:

  dualstack_server:
    type: OS::Nova::Server
    properties:
      image: { get_param: server_image }
      availability_zone: { get_param: availability_zone }
      flavor: m1.micro
      name: { get_param: server_name }
      key_name: { get_param: ssh_key }
      security_groups:
        - { get_param: secgrp }
      networks:
        - subnet: { get_param: ipv4_subnet }  # using v4 on first device for metadata and so on
        - subnet: { get_param: ipv6_subnet }  # v6 gets its own interface to have ordering of ip addresses to be used in pool members
      user_data_format: RAW
      user_data: { get_resource: cloud_init_ipv6 }

  cloud_init_ipv6:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
        - path: /etc/dhcp/dhclient6.conf
          content: "timeout 30;"
          #- path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
          #content: "network: {config: disabled}"
        - path: /etc/network/interfaces.d/lo.cfg
          content: |
              auto lo
              iface lo inet loopback
        - path: /etc/network/interfaces.d/ens4.cfg
          content: |
              iface ens4 inet6 auto
                  up sleep 5
                  up dhclient -1 -6 -cf /etc/dhcp/dhclient6.conf -lf /var/lib/dhcp/dhclient6.ens4.leases -v ens4 || true
        - path: /etc/systemd/system/whoami.service
          content: |
            [Unit]
            Description=Run whoamI service
            After=network.target
            [Service]
            Type=simple
            ExecStartPre=/bin/bash -c '/usr/bin/test -f /usr/local/bin/whoamI || /usr/bin/curl -Lo /usr/local/bin/whoamI https://github.com/containous/whoami/releases/download/1.0.0/whoamI'
            ExecStartPre=-/bin/chmod a+x /usr/local/bin/whoamI
            ExecStart=/usr/local/bin/whoamI -port 8000
            [Install]
            WantedBy=multi-user.target

        runcmd:
          - [ ifdown, ens4]
          - [ ifup, ens4]
          - [ systemctl, daemon-reload ]
          - [ systemctl, enable, whoami ]
          - [ systemctl, start, whoami ]

  lb_pool6_member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      address: { get_attr: [dualstack_server, networks, { get_param: network }, 1 ] }
      pool: { get_param: ipv6_lb_pool }
      protocol_port: 8000
      subnet: { get_param: ipv6_subnet }

  lb_pool4_member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      address: { get_attr: [dualstack_server, networks, { get_param: network }, 0 ] }
      pool: { get_param: ipv4_lb_pool }
      protocol_port: 8000
      subnet: { get_param: ipv4_subnet }
