heat_template_version: 2018-03-02

parameters:
  server_name:
    description: How to call the server
    type: string
  server_image:
    description: ID or name of the glance image to boot from
    type: string
  ssh_key:
    description: ID or name of your ssh key. Must exist in your OpenStack account.
    type: string
  secgrp:
    description: security group to use
    type: string
  network:
    description: network to use
    type: string
  ipv4_subnet:
    description: IPv4 subnet
    type: string
  ipv6_subnet:
    description: IPv6 subnet
    type: string
  ipv4_lb_pool:
    description: IPv4 LoadBalancerPool
    type: string
  ipv6_lb_pool:
    description: IPv6 LoadBalancerPool
    type: string
  availability_zone:
    description: Availability Zone to spawn server in
    type: string

resources:

  dualstack_server:
    type: OS::Nova::Server
    properties:
      image: { get_param: server_image }
      availability_zone: { get_param: availability_zone }
      flavor: m1.micro
      name: { get_param: server_name }
      key_name: { get_param: ssh_key }
      security_groups:
        - { get_param: secgrp }
      networks:
        - subnet: { get_param: ipv4_subnet }  # using v4 on first device for metadata and so on
        - subnet: { get_param: ipv6_subnet }  # v6 gets its own interface to have ordering of ip addresses to be used in pool members
      user_data_format: RAW
      user_data: { get_resource: cloud_init_ipv6 }

  cloud_init_ipv6:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        package_upgrade: true
        write_files:
        - path: /etc/netplan/60-ens4-cfg.yaml
          content: |
              network:
                version: 2
                renderer: networkd
                ethernets:
                  ens4:
                    dhcp6: yes

        - path: /etc/systemd/system/whoami.service
          content: |
              [Unit]
              Description=Run whoamI service
              After=network.target
              [Service]
              Type=simple
              ExecStartPre=/bin/bash -c '/usr/bin/test -f /usr/local/bin/whoamI || /usr/bin/curl -Lo /usr/local/bin/whoamI https://github.com/containous/whoami/releases/download/1.0.0/whoamI'
              ExecStartPre=-/bin/chmod a+x /usr/local/bin/whoamI
              ExecStart=/usr/local/bin/whoamI -port 8000
              [Install]
              WantedBy=multi-user.target

        runcmd:
          - '\netplan apply'
          - '\systemctl daemon-reload'
          - '\systemctl enable whoami'
          - '\systemctl start whoami'
          - '\shutdown -r now' # or set package_upgrade to false :)

  lb_pool6_member:
    type: OS::Octavia::PoolMember
    properties:
      address: { get_attr: [dualstack_server, networks, { get_param: network }, 1 ] }
      pool: { get_param: ipv6_lb_pool }
      protocol_port: 8000
      subnet: { get_param: ipv6_subnet }

  lb_pool4_member:
    type: OS::Octavia::PoolMember
    properties:
      address: { get_attr: [dualstack_server, networks, { get_param: network }, 0 ] }
      pool: { get_param: ipv4_lb_pool }
      protocol_port: 8000
      subnet: { get_param: ipv4_subnet }
